[package]
name = "competitive-programming-rust"
version = "0.1.0"
authors = ["ishii"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
